### ISSUE TITLE
Refresh the ontology cache when new terms are added.

### ISSUE THREAD

**Issue by EmmettSprecherP4** [Paradigm4/scidb4gh#17]
When adding an ontology term with "**register_ontology_term()**", the term does not appear in a subsequent call to "**get_ontology()**" until after manually updating the cache by calling "**search_ontology()**" with the "**updateCache = TRUE**" option.

**Comment by ksens** [comment]
During `register_ontology_term()`, the cache is now refreshed. See https://github.com/Paradigm4/scidb4gh/blob/master/R/functions.R#L326
