### ISSUE TITLE
dataset_version should not be specified as a column in register_variant

### ISSUE THREAD

**Issue by EmmettSprecherP4** [Paradigm4/scidb4gh#23]
At a customer site, the following script was used:

```R
  df_for_upload$dataset_version = as.integer(variantset_record['dataset_version'])
  cat("--------\nNow, registering", nrow(df_for_upload), "variants for variantset #", idx, "\n")
  register_variant(df = df_for_upload, dataset_version = version_num)
```

In this case, `dataset_version` is being specified twice. This should be the case as most `register_ENTITY` calls have a `dataset_version` parameter.

**Comment by ksens** [comment]
Fixed within the API. 

@EmmettSprecherP4 when you file a ticket for improving `test_register_variant()`, you can add a note that the test should fail if `dataset_version` is already supplied in the dataframe.
